version: "3.3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tdebd"
      POSTGRES_USER: "tdeadmin"
      POSTGRES_PASSWORD: "7140043"
      PGDATA: "/var/lib/postgresql/data/data/bd"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tdeadmin -d tdebd"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  server:
    build: server/
    depends_on:
      - postgres
    ports:
      - 90:5000
  tde:
    build: client/
    ports:
      - 80:3000
    depends_on:
      - postgres
      - server
  